-- ============================================================
-- stg_profiles.sql
-- Mục đích: Flatten JSON hồ sơ nhân viên từ RAW_1OFFICE_PROFILE
-- Source: RAW.RAW_1OFFICE_PROFILE (mỗi row chứa JSON array 500 profiles)
-- Output: 1 row = 1 nhân viên, đã dedup theo sync_time mới nhất
--
-- ⚠️  ĐÃ CHUYỂN TỪ BIGQUERY SANG SNOWFLAKE SYNTAX (Sprint 2 - Task 2.2):
--   BigQuery: JSON_VALUE(col,'$.key') → Snowflake: JSON_VALUE(f, '$.key')
--   BigQuery: SAFE.PARSE_DATE(...)   → Snowflake: TRY_TO_DATE(...)
--   BigQuery: UNNEST(...)            → Snowflake: LATERAL FLATTEN(...)
--   BigQuery: CAST(... AS INT64)     → Snowflake: ::int
--   BigQuery: CAST(... AS FLOAT64)   → Snowflake: ::float
-- ============================================================

with raw_source as (
    select * from {{ source('dwh_1office', 'raw_1office_profile') }}
),
flattened as (
    select
        sync_time,
        CAST(JSON_VALUE(f, '$.ID') AS INT64)                                                as ID,
        CAST(JSON_VALUE(f, '$.allow_1') AS INT64)                                           as allow_1,
        CAST(JSON_VALUE(f, '$.allow_10') AS INT64)                                          as allow_10,
        CAST(JSON_VALUE(f, '$.allow_13') AS INT64)                                          as allow_13,
        JSON_VALUE(f, '$.allow_14')                                       as allow_14,
        JSON_VALUE(f, '$.allow_19')                                       as allow_19,
        JSON_VALUE(f, '$.allow_2')                                        as allow_2,
        CAST(JSON_VALUE(f, '$.allow_20') AS INT64)                                          as allow_20,
        CAST(JSON_VALUE(f, '$.allow_4') AS INT64)                                           as allow_4,
        CAST(JSON_VALUE(f, '$.allow_7') AS INT64)                                           as allow_7,
        CAST(JSON_VALUE(f, '$.allow_9') AS INT64)                                           as allow_9,
        CAST(JSON_VALUE(f, '$.allow_salary') AS INT64)                                      as allow_salary,
        JSON_VALUE(f, '$.allow_salary_details')                           as allow_salary_details,
        CAST(JSON_VALUE(f, '$.api_position_id') AS INT64)                                   as api_position_id,
        JSON_VALUE(f, '$.attendace_code')                                 as attendace_code,
        JSON_VALUE(f, '$.bank_info')                                      as bank_info,
        CAST(JSON_VALUE(f, '$.birth_times') AS INT64)                                       as birth_times,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.birthday'))           as birthday,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.birthday_current'))   as birthday_current,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.birthday_now'))       as birthday_now,
        JSON_VALUE(f, '$.blood_group')                                    as blood_group,
        JSON_VALUE(f, '$.blood_pressure')                                 as blood_pressure,
        JSON_VALUE(f, '$.branch_address')                                 as branch_address,
        JSON_VALUE(f, '$.branch_code')                                    as branch_code,
        JSON_VALUE(f, '$.branch_name')                                    as branch_name,
        JSON_VALUE(f, '$.candidate_id')                                   as candidate_id,  -- ✅ Fix: đây là ID, không phải ngày
        JSON_VALUE(f, '$.certificate')                                    as certificate,
        JSON_VALUE(f, '$.certificate_status')                             as certificate_status,
        JSON_VALUE(f, '$.certificates_code')                              as certificates_code,
        JSON_VALUE(f, '$.certificates_count_released')                   as certificates_count_released,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.certificates_date_apply')) as certificates_date_apply,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.certificates_date_end'))   as certificates_date_end,
        JSON_VALUE(f, '$.certificates_document')                         as certificates_document,
        JSON_VALUE(f, '$.certificates_type')                              as certificates_type,
        JSON_VALUE(f, '$.certificates_version')                           as certificates_version,
        JSON_VALUE(f, '$.code')                                           as code,
        JSON_VALUE(f, '$.code_contract')                                  as code_contract,
        JSON_VALUE(f, '$.code_storage')                                   as code_storage,
        CAST(JSON_VALUE(f, '$.coefficient') AS INT64)                                       as coefficient,
        JSON_VALUE(f, '$.company_address')                                as company_address,
        JSON_VALUE(f, '$.company_code')                                   as company_code,
        JSON_VALUE(f, '$.company_name')                                   as company_name,
        JSON_VALUE(f, '$.company_tax')                                    as company_tax,
        JSON_VALUE(f, '$.concurrent_depart_ids')                         as concurrent_depart_ids,
        JSON_VALUE(f, '$.concurrent_position_ids')                       as concurrent_position_ids,
        JSON_VALUE(f, '$.cost_center')                                    as cost_center,
        JSON_VALUE(f, '$.created_by_id')                                  as created_by_id,
        JSON_VALUE(f, '$.current_address')                                as current_address,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.date_change_salary')) as date_change_salary,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.date_created'))       as date_created,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.date_created_certificate')) as date_created_certificate,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.date_finish_contract')) as date_finish_contract,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.date_join_now'))      as date_join_now,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.date_leave_from'))    as date_leave_from,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.date_leave_to'))      as date_leave_to,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.date_of_resignation')) as date_of_resignation,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.date_start_contract')) as date_start_contract,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.date_trigger_user'))  as date_trigger_user,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.date_updated'))       as date_updated,
        CAST(JSON_VALUE(f, '$.day_job') AS INT64)                                           as day_job,
        JSON_VALUE(f, '$.degree_place')                                   as degree_place,
        JSON_VALUE(f, '$.degree_specialization')                          as degree_specialization,
        JSON_VALUE(f, '$.degrees')                                        as degrees,
        CAST(JSON_VALUE(f, '$.department_api') AS INT64)                                    as department_api,
        JSON_VALUE(f, '$.department_business')                            as department_business,
        JSON_VALUE(f, '$.department_code')                                as department_code,
        JSON_VALUE(f, '$.department_full')                                as department_full,
        JSON_VALUE(f, '$.department_full_all')                            as department_full_all,
        JSON_VALUE(f, '$.department_id')                                  as department_id,
        JSON_VALUE(f, '$.department_main')                                as department_main,
        JSON_VALUE(f, '$.department_management_unit')                    as department_management_unit,
        CAST(JSON_VALUE(f, '$.department_num_id') AS INT64)                                 as department_num_id,
        JSON_VALUE(f, '$.department_parent')                              as department_parent,
        JSON_VALUE(f, '$.department_type_id')                             as department_type_id,
        JSON_VALUE(f, '$.desc')                                           as description_text,
        JSON_VALUE(f, '$.designation')                                    as designation,
        JSON_VALUE(f, '$.document_status')                                as document_status,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.due_date'))           as due_date,
        JSON_VALUE(f, '$.email')                                          as email,
        JSON_VALUE(f, '$.family_all')                                     as family_all,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.family_birthday'))    as family_birthday,
        JSON_VALUE(f, '$.family_dependent')                               as family_dependent,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.family_dependent_from_date')) as family_dependent_from_date,
        JSON_VALUE(f, '$.family_dependent_tax')                           as family_dependent_tax,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.family_dependent_to_date')) as family_dependent_to_date,
        JSON_VALUE(f, '$.family_desc')                                    as family_desc,
        JSON_VALUE(f, '$.family_gender')                                  as family_gender,
        JSON_VALUE(f, '$.family_name')                                    as family_name,
        JSON_VALUE(f, '$.family_phone')                                   as family_phone,
        JSON_VALUE(f, '$.family_relative_id')                             as family_relative_id,
        JSON_VALUE(f, '$.gender')                                         as gender,
        JSON_VALUE(f, '$.gps_location_ids')                               as gps_location_ids,
        JSON_VALUE(f, '$.heart_beat')                                     as heart_beat,
        JSON_VALUE(f, '$.height')                                         as height,
        JSON_VALUE(f, '$.home_address')                                   as home_address,
        JSON_VALUE(f, '$.image_private_back')                             as image_private_back,
        JSON_VALUE(f, '$.image_private_front')                            as image_private_front,
        JSON_VALUE(f, '$.is_econtract')                                   as is_econtract,
        JSON_VALUE(f, '$.job_bank_account')                               as job_bank_account,
        JSON_VALUE(f, '$.job_bank_account_name')                          as job_bank_account_name,
        JSON_VALUE(f, '$.job_bank_desc')                                  as job_bank_desc,
        JSON_VALUE(f, '$.job_bank_id')                                    as job_bank_id,
        JSON_VALUE(f, '$.job_contract')                                   as job_contract,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.job_date_end_review')) as job_date_end_review,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.job_date_join'))      as job_date_join,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.job_date_out'))       as job_date_out,
        JSON_VALUE(f, '$.job_out_reason')                                 as job_out_reason,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.job_reldate_join'))   as job_reldate_join,
        JSON_VALUE(f, '$.job_status')                                     as job_status,
        JSON_VALUE(f, '$.job_tax')                                        as job_tax,
        JSON_VALUE(f, '$.job_title')                                      as job_title,
        CAST(JSON_VALUE(f, '$.job_title_api') AS INT64)                                     as job_title_api,
        JSON_VALUE(f, '$.job_title_desc')                                 as job_title_desc,
        JSON_VALUE(f, '$.job_title_name')                                 as job_title_name,
        JSON_VALUE(f, '$.jobout_1')                                       as jobout_1,
        JSON_VALUE(f, '$.jobout_2')                                       as jobout_2,
        JSON_VALUE(f, '$.jobout_3')                                       as jobout_3,
        JSON_VALUE(f, '$.jobout_4')                                       as jobout_4,
        JSON_VALUE(f, '$.jobout_5')                                       as jobout_5,
        JSON_VALUE(f, '$.jobout_6')                                       as jobout_6,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.jobout_date_1'))      as jobout_date_1,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.jobout_date_2'))      as jobout_date_2,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.jobout_date_3'))      as jobout_date_3,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.jobout_date_4'))      as jobout_date_4,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.jobout_date_5'))      as jobout_date_5,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.jobout_date_6'))      as jobout_date_6,
        JSON_VALUE(f, '$.jobs')                                           as jobs,
        JSON_QUERY(f, '$.json_add_concurrent')                                    as json_add_concurrent,
        JSON_QUERY(f, '$.json_bankInfo')                                          as json_bankInfo,
        JSON_QUERY(f, '$.json_communist')                                         as json_communist,
        JSON_QUERY(f, '$.json_degrees')                                           as json_degrees,
        JSON_QUERY(f, '$.json_experience')                                        as json_experience,
        JSON_QUERY(f, '$.json_family')                                            as json_family,
        JSON_QUERY(f, '$.json_insurance')                                         as json_insurance,
        JSON_QUERY(f, '$.json_solves')                                            as json_solves,
        JSON_QUERY(f, '$.json_visa')                                              as json_visa,
        JSON_QUERY(f, '$.json_workPermit')                                        as json_workPermit,
        JSON_VALUE(f, '$.labor_group')                                    as labor_group,
        JSON_VALUE(f, '$.level_academic')                                 as level_academic,
        JSON_VALUE(f, '$.level_education_type')                           as level_education_type,
        JSON_VALUE(f, '$.level_id')                                       as level_id,
        CAST(JSON_VALUE(f, '$.level_num_id') AS INT64)                                      as level_num_id,
        JSON_VALUE(f, '$.level_school')                                   as level_school,
        JSON_VALUE(f, '$.live_manager_code')                              as live_manager_code,
        JSON_VALUE(f, '$.live_manager_id')                                as live_manager_id,
        JSON_VALUE(f, '$.marital_status')                                 as marital_status,
        JSON_VALUE(f, '$.military_service')                               as military_service,
        JSON_VALUE(f, '$.mobile')                                         as mobile,
        JSON_VALUE(f, '$.name')                                           as name,
        JSON_VALUE(f, '$.nationality')                                    as nationality,
        CAST(JSON_VALUE(f, '$.num_file') AS INT64)                                          as num_file,
        CAST(JSON_VALUE(f, '$.number_dependent') AS INT64)                                  as number_dependent,
        JSON_VALUE(f, '$.origin_state')                                   as origin_state,
        JSON_VALUE(f, '$.passport_code')                                  as passport_code,
        JSON_VALUE(f, '$.passport_code_place')                            as passport_code_place,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.passport_date_expire')) as passport_date_expire,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.passport_date_from')) as passport_date_from,
        JSON_VALUE(f, '$.passport_image_front')                           as passport_image_front,
        JSON_VALUE(f, '$.passport_type')                                  as passport_type,
        JSON_VALUE(f, '$.people')                                         as people,
        JSON_VALUE(f, '$.photo')                                          as photo,
        JSON_VALUE(f, '$.place_current')                                  as place_current,
        JSON_VALUE(f, '$.place_current_district_title')                  as place_current_district_title,
        JSON_VALUE(f, '$.place_current_province_title')                  as place_current_province_title,
        JSON_VALUE(f, '$.place_current_title')                            as place_current_title,
        JSON_VALUE(f, '$.place_home')                                     as place_home,
        JSON_VALUE(f, '$.place_home_code')                                as place_home_code,
        JSON_VALUE(f, '$.place_home_district_title')                     as place_home_district_title,
        JSON_VALUE(f, '$.place_home_province_title')                     as place_home_province_title,
        JSON_VALUE(f, '$.place_home_title')                               as place_home_title,
        JSON_VALUE(f, '$.place_of_birthday')                              as place_of_birthday,  -- ✅ Fix: đây là địa danh, không phải ngày
        CAST(JSON_VALUE(f, '$.position_api') AS INT64)                                      as position_api,
        JSON_VALUE(f, '$.position_id')                                    as position_id,
        JSON_VALUE(f, '$.position_parent_id')                             as position_parent_id,
        JSON_VALUE(f, '$.position_title')                                 as position_title,
        JSON_VALUE(f, '$.premium_code')                                   as premium_code,
        JSON_VALUE(f, '$.premium_number')                                 as premium_number,
        JSON_VALUE(f, '$.premium_personnel')                              as premium_personnel,
        JSON_VALUE(f, '$.premium_place')                                  as premium_place,
        JSON_VALUE(f, '$.premium_place_code')                             as premium_place_code,
        JSON_VALUE(f, '$.private_code')                                   as private_code,
        JSON_VALUE(f, '$.private_code_back')                              as private_code_back,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.private_code_date'))  as private_code_date,
        JSON_VALUE(f, '$.private_code_front')                             as private_code_front,
        JSON_VALUE(f, '$.private_code_place')                             as private_code_place,
        CAST(JSON_VALUE(f, '$.raw_user_id') AS INT64)                                       as raw_user_id,
        JSON_VALUE(f, '$.receive_16')                                     as receive_16,
        JSON_VALUE(f, '$.receive_2')                                      as receive_2,
        JSON_VALUE(f, '$.receive_22')                                     as receive_22,
        JSON_VALUE(f, '$.receive_23')                                     as receive_23,
        JSON_VALUE(f, '$.receive_24')                                     as receive_24,
        JSON_VALUE(f, '$.receive_3')                                      as receive_3,
        JSON_VALUE(f, '$.receive_4')                                      as receive_4,
        JSON_VALUE(f, '$.receive_5')                                      as receive_5,
        JSON_VALUE(f, '$.receive_7')                                      as receive_7,
        JSON_VALUE(f, '$.receive_8')                                      as receive_8,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.receive_date_16'))    as receive_date_16,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.receive_date_2'))     as receive_date_2,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.receive_date_22'))    as receive_date_22,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.receive_date_23'))    as receive_date_23,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.receive_date_24'))    as receive_date_24,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.receive_date_3'))     as receive_date_3,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.receive_date_4'))     as receive_date_4,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.receive_date_5'))     as receive_date_5,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.receive_date_7'))     as receive_date_7,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.receive_date_8'))     as receive_date_8,
        JSON_VALUE(f, '$.religious')                                      as religious,
        JSON_VALUE(f, '$.salaries')                                       as salaries,
        CAST(JSON_VALUE(f, '$.salary_10') AS FLOAT64)                                       as salary_10,
        CAST(JSON_VALUE(f, '$.salary_11') AS FLOAT64)                                       as salary_11,
        CAST(JSON_VALUE(f, '$.salary_12') AS FLOAT64)                                       as salary_12,
        CAST(JSON_VALUE(f, '$.salary_13') AS FLOAT64)                                       as salary_13,
        CAST(JSON_VALUE(f, '$.salary_14') AS FLOAT64)                                       as salary_14,
        CAST(JSON_VALUE(f, '$.salary_15') AS FLOAT64)                                       as salary_15,
        CAST(JSON_VALUE(f, '$.salary_16') AS FLOAT64)                                       as salary_16,
        CAST(JSON_VALUE(f, '$.salary_17') AS FLOAT64)                                       as salary_17,
        CAST(JSON_VALUE(f, '$.salary_3') AS FLOAT64)                                        as salary_3,
        CAST(JSON_VALUE(f, '$.salary_4') AS FLOAT64)                                        as salary_4,
        CAST(JSON_VALUE(f, '$.salary_6') AS FLOAT64)                                        as salary_6,
        CAST(JSON_VALUE(f, '$.salary_7') AS FLOAT64)                                        as salary_7,
        CAST(JSON_VALUE(f, '$.salary_8') AS FLOAT64)                                        as salary_8,
        CAST(JSON_VALUE(f, '$.salary_9') AS FLOAT64)                                        as salary_9,
        JSON_VALUE(f, '$.salary_area_id')                                 as salary_area_id,
        CAST(JSON_VALUE(f, '$.salary_min_area') AS FLOAT64)                                 as salary_min_area,
        JSON_VALUE(f, '$.salary_premium_base')                            as salary_premium_base,
        CAST(JSON_VALUE(f, '$.salary_real') AS FLOAT64)                                     as salary_real,
        CAST(JSON_VALUE(f, '$.salary_total') AS FLOAT64)                                    as salary_total,
        JSON_VALUE(f, '$.specialization')                                 as specialization,
        JSON_VALUE(f, '$.state_code')                                     as state_code,
        JSON_VALUE(f, '$.state_name')                                     as state_name,
        JSON_VALUE(f, '$.type_contract')                                  as type_contract,
        JSON_VALUE(f, '$.updated_by_id')                                  as updated_by_id,  -- ✅ Fix: đây là ID, không phải ngày
        JSON_VALUE(f, '$.user_id')                                        as user_id,
        JSON_VALUE(f, '$.weight')                                         as weight,
        SAFE.PARSE_DATE('%d/%m/%Y', JSON_VALUE(f, '$.welfares_date_force')) as welfares_date_force,
        JSON_VALUE(f, '$.welfares_money')                                 as welfares_money,
        JSON_VALUE(f, '$.welfares_reason')                                as welfares_reason,
        JSON_VALUE(f, '$.welfares_type')                                  as welfares_type,
        JSON_VALUE(f, '$.work_place')                                     as work_place,
        JSON_VALUE(f, '$.work_place_address')                             as work_place_address,
        JSON_VALUE(f, '$.work_type')                                      as work_type,
        CAST(JSON_VALUE(f, '$.year_join') AS FLOAT64)                                       as year_join,
        CAST(JSON_VALUE(f, '$.year_work_experience') AS INT64)                              as year_work_experience,
        CAST(JSON_VALUE(f, '$.year_work_experience_now') AS FLOAT64)                        as year_work_experience_now

    from raw_source,
    -- ✅ Snowflake syntax: LATERAL FLATTEN thay vì UNNEST
    UNNEST(JSON_QUERY_ARRAY(raw_data, '$.data')) AS f
)

select * from flattened
-- Giữ bản ghi mới nhất theo sync_time cho mỗi nhân viên
qualify row_number() over (partition by ID order by sync_time desc) = 1
